import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { Navbar } from "./Navbar";
import AuthProvider from "./auth/provider";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ['400', '500']
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="winter">
      <body
        className={roboto.className} 
      >
        <AuthProvider>
      <Navbar />
        {children}
        </AuthProvider>
      </body>
    </html>
  );
}
